version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/cloud_assessment1
    ports:
      - "8000:8000"
    depends_on:
      - db
      
  db:
    image: mysql:8.0.2
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'visitors'
       MYSQL_USER: 'mysql'
       MYSQL_ROOT_PASSWORD: 'Admin1234!'
       MYSQL_PASSWORD: 'Admin1234!'
    expose:
      - "3306"